default: &default
  adapter: postgresql
  host: localhost
  username: pguser
  password: pguser
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: companymanager_database_development
  host: localhost

test:
  <<: *default
  database: companymanager_database_test
  host: localhost

production:
  <<: *default
  database: companymanager_database_production
  host: localhost
